[EOPS-678] Modify v_invalid_concept_ids pg migration
all-of-us/ehr-ops pull request #29
Opened 2021-12-18 13:18 UTC by na2960

- Modifies the invalid_concept_ids query

2021-12-21 17:41 UTC, jp3477 approved these changes
This looks good to me!

2021-12-21 18:26 UTC, xj2193 commented on sql/ehr_metrics/invalid_concept_ids/invalid_concept_ids.sql
> +  'visit_occurrence_id' AS table_name,
We want to keep 'visit_occurrence' as the table name.

2021-12-21 18:37 UTC, xj2193 requested changes
Thanks @na2960 , the only part needs to be changed are the table_names column. Could you revert them back to the omop table names. This field is for indicating which OMOP table has invalid concept id.

2021-12-23 18:17 UTC, na2960 commented
> Thanks @na2960 , the only part needs to be changed are the table_names column. Could you revert them back to the omop table names. This field is for indicating which OMOP table has invalid concept id.

Oh yes, I forgot to revert this back. Should be updated now w/ the last commit. Thanks Zoey!

2021-12-23 18:19 UTC, na2960 commented
Updated table_name strings to reflect table itself (vs ...._id)

2022-01-04 19:15 UTC, jp3477 commented
Sorry, accidentally closed it! It's reopened now.

2022-04-29 16:55 UTC, closed without merging